name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  build-and-deploy:
    name: Build and Deploy Flutter Web
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4


      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true


      # 3. Check Flutter version
      - name: Check Flutter version
        run: |
          flutter --version
          dart --version


      # 4. Install dependencies
      - name: Install Flutter dependencies
        working-directory: frontend
        run: |
          flutter pub get


      # 5. Build Flutter Web
      - name: Build Flutter Web
        working-directory: frontend
        run: |
          flutter build web --release


      # 6. Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key

          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts


      # 7. Prepare EC2 frontend directory
      - name: Prepare EC2
        run: |
          ssh \
            -i ~/.ssh/ec2_key \
            -o StrictHostKeyChecking=yes \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
            "
              sudo mkdir -p /var/www/html
              sudo rm -rf /var/www/html/*
              rm -rf /tmp/flutter-web
              mkdir -p /tmp/flutter-web
            "

      # 8. Upload Flutter Web
      - name: Upload Flutter Web to EC2
        run: |
          scp \
            -i ~/.ssh/ec2_key \
            -o StrictHostKeyChecking=yes \
            -r frontend/build/web/* \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/tmp/flutter-web/

      # 9. Deploy files to Nginx
      - name: Deploy files to Nginx
        run: |
          ssh \
            -i ~/.ssh/ec2_key \
            -o StrictHostKeyChecking=yes \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
            "
              sudo mkdir -p /var/www/html
              sudo cp -r /tmp/flutter-web/* /var/www/html/
              sudo chown -R www-data:www-data /var/www/html
              sudo rm -rf /tmp/flutter-web
              sudo nginx -t
              sudo systemctl reload nginx
            "

      # 10. Deployment completed
      - name: Deployment completed
        run: |
          echo "========================================"
          echo "Frontend deployment completed"
          echo "========================================"